# This is a basic workflow to help you get started with Actions
name: webhook-trigger

on:
  repository_dispatch:
    types: 
      - build
  # push:
    # branches:
      # - feature/add-build-webhook

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: echo env
      run: echo "${{ secrets.API_URL }}" > .env
    - name: Install modules
      run: yarn
    - name: Run build
      run:  ./node_modules/.bin/gridsome build
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr
        path: dist/
        remote_path: ${{secrets.DEPLOY_PATH}}
        remote_host: ${{secrets.SSH_HOSTNAME}}
        remote_port: ${{secrets.SSH_PORT}}
        remote_user: ${{secrets.SSH_USERNAME}}
        remote_key: ${{secrets.SSH_PRIVATE_KEY}}
    - name: Setup Git Config
      run: |
        git config --local user.email "1858830+retrorocket@users.noreply.github.com"
        git config --local user.name "retrorocket"
    - name: Commit files
      continue-on-error: true
      run: |
        git add . && git commit -m "Update from Actions" -a ; git push origin master
