# This is a basic workflow to help you get started with Actions
name: webhook-trigger

on:
  repository_dispatch:
    types: 
      - build
  # push:
    # branches:
      # - feature/add-build-webhook

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: echo env
      run: echo "${{ secrets.API_URL }}" > .env
    - name: Install modules
      run: yarn
    - name: Run build
      run:  ./node_modules/.bin/gridsome build
    - name: Deploy to test
      uses: trendyminds/github-actions-rsync@master
      with:
        RSYNC_OPTIONS: -avz
        RSYNC_TARGET: ${{secrets.DEPLOY_PATH}}
        RSYNC_SOURCE: ./dist/
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_USERNAME: ${{secrets.SSH_USERNAME}}
        SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}
    - name: Setup Git Config
      run: |
        git config --local user.email "1858830+retrorocket@users.noreply.github.com"
        git config --local user.name "retrorocket"
    - name: Commit files
      continue-on-error: true
      run: |
        git add . && git commit -m "Update from Actions" -a ; git push origin master
