# This is a basic workflow to help you get started with Actions
name: webhook-trigger

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout other repo
        uses: actions/checkout@v2
        with:
          repository: retrorocket/blog-contents
          path: content
          token: ${{ secrets.PERSONAL_TOKEN }}
      #- name: Update submodule
      #  run: |
      #    git submodule update --remote ./content/
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn install
      - name: Run build
        run: yarn gridsome build > /dev/null
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --exclude "/archives" --exclude "/assets"
          path: dist/
          remote_path: ${{secrets.DEPLOY_PATH}}
          remote_host: ${{secrets.SSH_HOSTNAME}}
          remote_port: ${{secrets.SSH_PORT}}
          remote_user: ${{secrets.SSH_USERNAME}}
          remote_key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: rsync deployments archives
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: dist/archives/
          remote_path: ${{secrets.DEPLOY_PATH}}/archives
          remote_host: ${{secrets.SSH_HOSTNAME}}
          remote_port: ${{secrets.SSH_PORT}}
          remote_user: ${{secrets.SSH_USERNAME}}
          remote_key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: rsync deployments assets
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: dist/assets/
          remote_path: ${{secrets.DEPLOY_PATH}}/assets
          remote_host: ${{secrets.SSH_HOSTNAME}}
          remote_port: ${{secrets.SSH_PORT}}
          remote_user: ${{secrets.SSH_USERNAME}}
          remote_key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Commit files
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config --local user.email "1858830+retrorocket@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "Add changes from actions"
          fi
      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
